"use client";
import {useState} from "react";
type Tx={label:string;merchant:string;category:string;amount:number;riskScore:number;requiresApproval:boolean};
const samples:Tx[]=[{label:"Safe groceries",merchant:"FreshMart",category:"groceries",amount:1280,riskScore:12,requiresApproval:false},{label:"Expensive electronics",merchant:"TechHub",category:"electronics",amount:12999,riskScore:22,requiresApproval:false},{label:"Unknown merchant",merchant:"UnknownStore",category:"software",amount:3200,riskScore:35,requiresApproval:false},{label:"High risk transaction",merchant:"TechHub",category:"electronics",amount:1800,riskScore:91,requiresApproval:false}];
const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
export default function Home(){
 const [policy,setPolicy]=useState("Let my agent automatically spend up to ₹2,000 on groceries from trusted merchants. Electronics require approval. Never let autonomous spending exceed ₹5,000 per transaction and ₹25,000 per month.");
 const [tx,setTx]=useState(samples[0]),[result,setResult]=useState<any>(),[simulation,setSimulation]=useState<any>(),[interpreted,setInterpreted]=useState<any>(),[whatIf,setWhatIf]=useState<any>(),[execution,setExecution]=useState<any>(),[securityTest,setSecurityTest]=useState<any>();
 const [limit,setLimit]=useState(5000),[busy,setBusy]=useState(false),[executing,setExecuting]=useState(false),[securityTesting,setSecurityTesting]=useState(false);
 async function post(path:string,body:any){const r=await fetch(path,{method:"POST",headers:{"Content-Type":"application/json"},cache:"no-store",body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw Error(d?.error||"Request failed");return d}
 async function evaluate(){setBusy(true);setExecution(null);try{const d=await post("/api/evaluate",{policyText:policy,transaction:tx});setResult(d);await post("/api/audit",{transaction:tx,firewall:d,execution:{attempted:false,executed:false}})}catch(e){console.error(e)}finally{setBusy(false)}}
 async function interpret(){setBusy(true);try{setInterpreted(await post("/api/interpret",{policyText:policy}))}catch(e){console.error(e)}finally{setBusy(false)}}
 async function simulate(){setBusy(true);try{setSimulation(await post("/api/simulate",{policyText:policy}))}catch(e){console.error(e)}finally{setBusy(false)}}
 async function compare(){setBusy(true);try{setWhatIf(await post("/api/whatif",{policyText:policy,globalLimit:limit}))}catch(e){console.error(e)}finally{setBusy(false)}}
 async function executePayment(approved=false){setExecuting(true);setExecution(null);try{const safe={label:String(tx.label),merchant:String(tx.merchant),category:String(tx.category),amount:Number(tx.amount),riskScore:Number(tx.riskScore),requiresApproval:Boolean(tx.requiresApproval)};const d=await post("/api/razorpay/order",{policyText:policy,transaction:safe,humanApproved:approved});setExecution(d);if(d.firewall)await post("/api/audit",{transaction:safe,firewall:d.firewall,humanApproved:approved,execution:{attempted:true,executed:Boolean(d.executed),razorpayOrderId:d?.razorpay?.orderId||null,realMoneyMoved:Boolean(d?.audit?.realMoneyMoved)}})}catch(e:any){setExecution({success:false,executed:false,message:e?.message||"Execution failed"})}finally{setExecuting(false)}}
 async function security(){setSecurityTesting(true);try{setSecurityTest(await post("/api/security-test",{policyText:policy,transaction:{label:"Tampered payment",merchant:"TechHub",category:"electronics",amount:12999,riskScore:22,requiresApproval:false},claimedDecision:"ALLOW"}))}catch(e:any){setSecurityTest({success:false,message:e?.message})}finally{setSecurityTesting(false)}}
 const p=interpreted?.policy||result?.policy,c=simulation?.counts||{ALLOW:0,REVIEW:0,BLOCK:0},a=simulation?.analyzed||0,success=execution?.success&&execution?.executed;
 return <main><header><div className="logo">Agent<span>Pay</span> Firewall</div><div className="badge">● FINANCIAL CONTROL PLANE</div></header><div className="wrap">
 <div className="hero"><div><div className="eyebrow">FINANCIAL CONTROL PLANE FOR AI AGENTS</div><h1>Give AI access to money.<br/><em>Keep humans in control.</em></h1><p>AI interprets intent. Deterministic controls authorize money. Every decision is explainable, bounded, gated and auditable.</p></div><div className="heroCard"><small>FIREWALL STATUS</small><b>PROTECTED</b><span>Policy engine • Online</span></div></div>
 <div className="metrics"><M t="DECISIONS" v={a}/><M t="AUTO APPROVED" v={c.ALLOW}/><M t="HUMAN REVIEW" v={c.REVIEW}/><M t="VALUE BLOCKED" v={money(simulation?.blockedValue)}/></div>
 <div className="grid">
 <section className="card"><Title n="01" h="Define financial policy" s="Human intent → enforceable controls"/><textarea value={policy} onChange={e=>{setPolicy(e.target.value);setResult(null);setExecution(null)}}/><button className="secondary full" onClick={interpret} disabled={busy}>{busy?"Working…":"Interpret policy →"}</button>{p&&<div className="aiPolicy"><div className="aiHead"><b>POLICY UNDERSTOOD</b><span>{interpreted?.source||"Compiled policy"}</span></div>{(interpreted?.interpretation||[]).map((x:string,i:number)=><div className="explain" key={i}><b>✓</b><span>{x}</span></div>)}<div className="aiRules"><Rule n="GLOBAL CAP" v={money(p.globalLimit)}/><Rule n="MONTHLY BUDGET" v={money(p.monthlyBudget)}/><Rule n="APPROVAL ABOVE" v={money(p.approvalAbove)}/><Rule n="GROCERIES" v={money(p.categoryLimits?.groceries)}/><Rule n="ELECTRONICS" v={p.categoryLimits?.electronics===0?"BLOCKED":"HUMAN APPROVAL"}/></div></div>}<div className="policy"><Rule n="GLOBAL CAP" v={money(p?.globalLimit||5000)}/><Rule n="MONTHLY BUDGET" v={money(p?.monthlyBudget||25000)}/><Rule n="APPROVAL ABOVE" v={money(p?.approvalAbove||5000)}/><Rule n="GROCERIES" v={money(p?.categoryLimits?.groceries||2000)}/></div><button className="primary full" onClick={simulate} disabled={busy}>Run 120-transaction simulation →</button></section>
 <section className="card"><Title n="02" h="Intercept payment intent" s="Every monetary action passes through the firewall"/><div className="chips">{samples.map(s=><button key={s.label} className={tx.label===s.label?"active":""} onClick={()=>{setTx(s);setResult(null);setExecution(null)}}>{s.label}</button>)}</div><div className="intent"><Rule n="MERCHANT" v={tx.merchant}/><Rule n="CATEGORY" v={tx.category}/><Rule n="AMOUNT" v={money(tx.amount)}/><Rule n="RISK" v={`${tx.riskScore}/100`}/></div><button className="primary full" onClick={evaluate} disabled={busy||executing}>{busy?"Evaluating…":"Evaluate payment request"}</button>{result?.decision&&<div className={`result ${String(result.decision).toLowerCase()}`}><div className="decisionRow"><div><small>FIREWALL DECISION</small><strong>{result.decision}</strong></div><div className="decisionIcon">{result.decision==="ALLOW"?"✓":result.decision==="BLOCK"?"×":"!"}</div></div><p>{result.decision==="ALLOW"?"Payment permitted under current policy.":result.decision==="BLOCK"?"Payment blocked before money can move.":"Human confirmation is required before money can move."}</p><div className="checks">{(result.checks||[]).map((x:any[],i:number)=><div key={i}><span className={String(x[1]).toLowerCase()}>{x[1]}</span><div><b>{x[0]}</b><small>{x[2]}</small></div></div>)}</div>{result.decision==="ALLOW"&&!success&&<button className="primary full" onClick={()=>executePayment()} disabled={executing}>Execute {money(tx.amount)} via Razorpay →</button>}{result.decision==="REVIEW"&&!execution&&<div className="approval"><b>HUMAN-IN-THE-LOOP GATE</b><strong>Human approval required</strong><p>The firewall will not call Razorpay until a human explicitly approves this transaction.</p><button className="primary full" onClick={()=>executePayment(true)} disabled={executing}>Approve & Execute {money(tx.amount)} →</button></div>}{success&&<div className="execution"><b>✓ RAZORPAY TEST ORDER CREATED</b><strong>Payment execution authorized</strong><code>{execution?.razorpay?.orderId}</code><small>✓ Server-side firewall re-check passed<br/>✓ Razorpay Test Mode order created<br/>✓ No real money moved</small></div>}{execution&&!success&&<div className="stopped"><b>Razorpay execution stopped</b><small>{execution.message}</small></div>}</div>}</section>
 <section className="card"><Title n="03" h="Decision audit trail" s="Explainable, bounded, gated, auditable"/><div className="timeline">{result?.decision?["INTENT_RECEIVED","POLICY_COMPILED","RISK_EVALUATED","POLICY_DECISION","AUDIT_COMMITTED"].map((x,i)=><div key={x}><i>{i+1}</i><span><b>{x}</b><small>{i===0?"Payment request received":i===1?"Natural-language policy converted to rules":i===2?`Risk score ${tx.riskScore}/100 evaluated`:i===3?`Final decision: ${result.decision}`:"Decision record written"}</small></span></div>):<div className="empty">Evaluate a transaction to generate the decision trail.</div>}</div></section>
 <section className="card"><Title n="04" h="Policy simulation" s="Measure the financial effect before deployment"/>{simulation?<><div className="simgrid"><Rule n="TRANSACTIONS" v={a}/><Rule n="APPROVED" v={c.ALLOW}/><Rule n="REVIEW" v={c.REVIEW}/><Rule n="BLOCKED" v={c.BLOCK}/></div><div className="bar"><span style={{width:`${c.ALLOW/a*100||0}%`}}/><span style={{width:`${c.REVIEW/a*100||0}%`}}/><span style={{width:`${c.BLOCK/a*100||0}%`}}/></div><div className="impact"><Rule n="VALUE APPROVED" v={money(simulation.approvedValue)}/><Rule n="VALUE BLOCKED" v={money(simulation.blockedValue)}/></div>{simulation.metrics&&<div className="perf"><small>FIREWALL PERFORMANCE</small><div className="perfgrid"><Metric n="AUTONOMOUS" v={`${simulation.metrics.autonomousApprovalRate.toFixed(1)}%`}/><Metric n="HUMAN REVIEW" v={`${simulation.metrics.humanReviewRate.toFixed(1)}%`}/><Metric n="BLOCKED" v={`${simulation.metrics.blockRate.toFixed(1)}%`}/><Metric n="HIGH-RISK CONTAINMENT" v={`${simulation.metrics.highRiskContainmentRate.toFixed(0)}%`}/><Metric n="VALUE PROTECTED" v={money(simulation.protectedValue)}/></div></div>}</>:<div className="empty">Run the simulation to see how the policy behaves across a batch.</div>}</section>
 <section className="card whatif"><Title n="05" h="Policy What-If" s="Change one control and measure the financial consequence"/><div className="sliderHead"><div><small>GLOBAL AUTONOMOUS LIMIT</small><b>{money(limit)}</b></div><input type="range" min="1000" max="15000" step="500" value={limit} onChange={e=>setLimit(Number(e.target.value))}/></div><button className="secondary full" onClick={compare} disabled={busy}>Compare policy impact →</button>{whatIf&&<div className="compare"><div className="compareHead"><span>METRIC</span><span>CURRENT</span><span>NEW POLICY</span></div>{[["Auto approved",whatIf.current.counts.ALLOW,whatIf.whatIf.counts.ALLOW],["Human review",whatIf.current.counts.REVIEW,whatIf.whatIf.counts.REVIEW],["Blocked",whatIf.current.counts.BLOCK,whatIf.whatIf.counts.BLOCK],["Value approved",money(whatIf.current.approvedValue),money(whatIf.whatIf.approvedValue)],["Protected value",money(whatIf.current.protectedValue),money(whatIf.whatIf.protectedValue)]].map(r=><div className="compareRow" key={r[0]}><span>{r[0]}</span><b>{r[1]}</b><b>{r[2]}</b></div>)}</div>}</section></div>
 <section className="card security"><Title n="06" h="Firewall integrity test" s="Prove that the browser cannot authorize money"/><div className="securityGrid"><div><small>ATTACKER CLAIM</small><b>ALLOW</b><span>Malicious frontend attempts to authorize ₹12,999.</span></div><div>→</div><div><small>SERVER DECISION</small><b>BLOCK</b><span>Razorpay remains unreachable.</span></div></div><button className="secondary full" onClick={security} disabled={securityTesting}>{securityTesting?"Testing firewall integrity…":"Run tamper-resistance test →"}</button>{securityTest?.success&&<div className="attack"><b>✓ ATTACK BLOCKED</b><p>Frontend claimed: <strong>{securityTest.attack.claimedDecision}</strong><br/>Server decided: <strong>{securityTest.attack.actualDecision}</strong><br/>Tampering detected: <strong>YES</strong><br/>Razorpay called: <strong>NO</strong></p>{securityTest.message}</div>}</section>
 <footer>AgentPay Firewall • Synthetic data • No real money moves • AI interprets; deterministic controls authorize</footer></div></main>}
function Title({n,h,s}:{n:string,h:string,s:string}){return <div className="title"><span>{n}</span><div><h2>{h}</h2><small>{s}</small></div></div>}
function Rule({n,v}:{n:string,v:any}){return <div><small>{n}</small><b>{v}</b></div>}
function M({t,v}:{t:string,v:any}){return <div className="metric"><small>{t}</small><b>{v}</b></div>}
function Metric({n,v}:{n:string,v:any}){return <div className="metricBox"><b>{v}</b><small>{n}</small></div>}
